--  Create custom types for better data integrity
CREATE TYPE pill_status_enum AS ENUM ('taken', 'missed');
CREATE TYPE flow_intensity_enum AS ENUM ('none', 'light', 'medium', 'heavy');
CREATE TYPE mood_enum AS ENUM ('happy', 'neutral', 'sad', 'anxious', 'energetic');

-- Create the health_logs table
CREATE TABLE public.health_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    pill_status pill_status_enum NULL,
    flow_intensity flow_intensity_enum NULL,
    symptoms TEXT[] NULL,
    mood mood_enum NULL,
    notes TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add a unique constraint to ensure a user can only have one log per day
ALTER TABLE public.health_logs
ADD CONSTRAINT health_logs_user_id_date_key UNIQUE (user_id, date);

-- Add comments to the table and columns for clarity
COMMENT ON TABLE public.health_logs IS 'Stores daily health tracking data for users.';
COMMENT ON COLUMN public.health_logs.user_id IS 'Foreign key to the user who created the log.';
COMMENT ON COLUMN public.health_logs.date IS 'The specific date the health log is for.';
COMMENT ON COLUMN public.health_logs.pill_status IS 'Status of daily pill intake.';
COMMENT ON COLUMN public.health_logs.flow_intensity IS 'Intensity of menstrual flow for the day.';
COMMENT ON COLUMN public.health_logs.symptoms IS 'Array of symptoms experienced on this day.';
COMMENT ON COLUMN public.health_logs.mood IS 'User-reported mood for the day.';
COMMENT ON COLUMN public.health_logs.notes IS 'Optional text notes for diet, exercise, etc.';

-- Add an index on user_id for fast lookups and RLS performance
CREATE INDEX idx_health_logs_user_id ON public.health_logs(user_id);

-- Create a trigger to automatically update the updated_at timestamp
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_health_logs_updated
BEFORE UPDATE ON public.health_logs
FOR EACH ROW
EXECUTE PROCEDURE public.handle_updated_at();


-- Enable Row Level Security (RLS)
ALTER TABLE public.health_logs ENABLE ROW LEVEL SECURITY;

-- Create policies for RLS
-- 1. Users can insert their own health logs
CREATE POLICY "Users can insert their own health logs"
ON public.health_logs
FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- 2. Users can view their own health logs
CREATE POLICY "Users can view their own health logs"
ON public.health_logs
FOR SELECT
USING (auth.uid() = user_id);

-- 3. Users can update their own health logs
CREATE POLICY "Users can update their own health logs"
ON public.health_logs
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- 4. Users can delete their own health logs
CREATE POLICY "Users can delete their own health logs"
ON public.health_logs
FOR DELETE
USING (auth.uid() = user_id); 