import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import React from 'react';
import { FontLoader } from './components/FontLoader';

// Instantiate Inter font with desired weights and subsets
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
  weight: ['400', '600', '700'],
});

export const metadata: Metadata = {
  title: "Web - Carepop Monorepo",
  description: "Generated by create-turbo",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <FontLoader />
        {children}
      </body>
    </html>
  );
}

export default RootLayout;
