-- Add detailed fields to appointment_reports table
ALTER TABLE public.appointment_reports
ADD COLUMN purpose_of_visit TEXT NULL,
ADD COLUMN symptoms_reported TEXT NULL,
ADD COLUMN vitals_blood_pressure TEXT NULL,
ADD COLUMN vitals_temperature TEXT NULL,
ADD COLUMN vitals_weight TEXT NULL,
ADD COLUMN vitals_height TEXT NULL,
ADD COLUMN vitals_other TEXT NULL,
ADD COLUMN findings_summary TEXT NULL,
ADD COLUMN diagnoses TEXT NULL,
ADD COLUMN recommendations_summary TEXT NULL,
ADD COLUMN treatment_plan TEXT NULL,
ADD COLUMN lifestyle_recommendations TEXT NULL,
ADD COLUMN medications_prescribed TEXT NULL,
ADD COLUMN tests_ordered TEXT NULL,
ADD COLUMN referrals TEXT NULL,
ADD COLUMN follow_up_date TEXT NULL,
ADD COLUMN follow_up_notes TEXT NULL,
ADD COLUMN additional_notes TEXT NULL; 