-- Migration to create the form engine tables and pre-populate with templates.

-- 1. Form Templates Table
-- Defines the types of forms available (e.g., "SOAP Note", "Intake Form").
CREATE TABLE public.form_templates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    -- The structure of the form, defining its fields, types, labels, etc.
    fields_definition JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
COMMENT ON TABLE public.form_templates IS 'Defines the structure of dynamic medical forms.';
ALTER TABLE public.form_templates ENABLE ROW LEVEL SECURITY;

-- RLS Policies: Admins can manage, authenticated users can read.
CREATE POLICY "Admins can manage form templates" ON public.form_templates FOR ALL USING (public.is_admin(auth.uid()));
CREATE POLICY "Authenticated users can read templates" ON public.form_templates FOR SELECT USING (auth.role() = 'authenticated');


-- 2. Pre-populate with our 5 defined forms.
-- Using $$ dollar-quoting to safely insert JSON strings.
INSERT INTO public.form_templates (name, description, fields_definition) VALUES
('Family Planning (FP) Form 1 - Initial Assessment', 'A comprehensive assessment record for family planning clients, based on the DOH FP Form 1. To be used for a client''s first visit.', $$
{
  "fields": [
    { "type": "section", "title": "Client Identification", "fields": [{ "name": "philhealth_id", "label": "PhilHealth ID", "type": "text" }, { "name": "client_id", "label": "Client ID", "type": "text" }, { "name": "nhts_id", "label": "NHTS ID", "type": "text" }, { "name": "4ps_id", "label": "4Ps ID", "type": "text" }] },
    { "type": "section", "title": "Client Information", "fields": [{ "name": "client_last_name", "label": "Last Name", "type": "text" }, { "name": "client_given_name", "label": "Given Name", "type": "text" }, { "name": "client_middle_name", "label": "Middle Name", "type": "text" }, { "name": "client_dob", "label": "Date of Birth", "type": "date" }, { "name": "client_age", "label": "Age", "type": "number" }, { "name": "client_education", "label": "Educational Attainment", "type": "text" }, { "name": "client_occupation", "label": "Occupation", "type": "text" }, { "name": "client_address_street", "label": "Street", "type": "text" }, { "name": "client_address_barangay", "label": "Barangay", "type": "text" }, { "name": "client_address_city", "label": "Municipality/City", "type": "text" }, { "name": "client_address_province", "label": "Province", "type": "text" }, { "name": "client_contact_number", "label": "Contact Number", "type": "text" }, { "name": "client_civil_status", "label": "Civil Status", "type": "text" }, { "name": "client_religion", "label": "Religion", "type": "text" }] },
    { "type": "section", "title": "Spouse Information", "fields": [{ "name": "spouse_last_name", "label": "Last Name", "type": "text" }, { "name": "spouse_given_name", "label": "Given Name", "type": "text" }, { "name": "spouse_middle_name", "label": "Middle Name", "type": "text" }, { "name": "spouse_dob", "label": "Date of Birth", "type": "date" }, { "name": "spouse_age", "label": "Age", "type": "number" }, { "name": "spouse_occupation", "label": "Occupation", "type": "text" }] },
    { "type": "section", "title": "Family and Planning", "fields": [{ "name": "num_living_children", "label": "No. of Living Children", "type": "number" }, { "name": "plan_more_children", "label": "Plan to have more children?", "type": "radio", "options": ["Yes", "No"] }, { "name": "avg_monthly_income", "label": "Average Monthly Income", "type": "number" }, { "name": "client_type", "label": "Type of Client", "type": "radio", "options": ["New Acceptor", "Changing Method", "Changing Clinic", "Continuing User", "Restart"] }, { "name": "fp_reason", "label": "Reason for FP", "type": "radio", "options": ["Spacing", "Limiting", "Others"] }, { "name": "fp_reason_specify", "label": "If others, specify", "type": "text" }] },
    { "type": "section", "title": "Method Currently Used (or for Changing Method)", "fields": [{ "name": "current_method", "label": "Select all applicable", "type": "checkbox", "options": ["COC", "POP", "Injectable", "Implant", "IUD", "BOM/CMM", "BBT", "SDM", "LAM", "Condom", "BTL", "NSV", "Others"] }, { "name": "current_method_specify", "label": "If others, specify", "type": "text" }] },
    { "type": "section", "title": "I. Medical History", "subtitle": "Does the client have any of the following?", "fields": [{ "name": "med_hist_headache", "label": "Severe headache / migraine", "type": "boolean" }, { "name": "med_hist_stroke_heart", "label": "History of stroke / heart attack / hypertension", "type": "boolean" }, { "name": "med_hist_hematoma", "label": "Non-traumatic hematoma / frequent bruising or gum bleeding", "type": "boolean" }, { "name": "med_hist_breast_cancer", "label": "History of breast cancer / breast mass", "type": "boolean" }, { "name": "med_hist_chest_pain", "label": "Severe chest pains", "type": "boolean" }, { "name": "med_hist_cough", "label": "Cough for more than 14 days", "type": "boolean" }, { "name": "med_hist_jaundice", "label": "Jaundice", "type": "boolean" }, { "name": "med_hist_vaginal_bleeding", "label": "Unexplained vaginal bleeding", "type": "boolean" }, { "name": "med_hist_vaginal_discharge", "label": "Abnormal vaginal discharge", "type": "boolean" }, { "name": "med_hist_medication_intake", "label": "Intake of phenobarbital (anti-seizure) or rifampicin (anti-TB)", "type": "boolean" }, { "name": "med_hist_smoker", "label": "Is the client a SMOKER?", "type": "boolean" }, { "name": "med_hist_disability", "label": "With Disability?", "type": "boolean" }, { "name": "med_hist_disability_specify", "label": "If yes, specify", "type": "text" }] },
    { "type": "section", "title": "II. Obstetrical History", "fields": [{ "name": "obs_hist_pregnancies", "label": "Number of pregnancies: G", "type": "number" }, { "name": "obs_hist_live_births", "label": "Live Births", "type": "number" }, { "name": "obs_hist_premature", "label": "Premature", "type": "number" }, { "name": "obs_hist_abortions", "label": "Abortion", "type": "number" }, { "name": "obs_hist_living_children", "label": "Living Children", "type": "number" }, { "name": "obs_hist_last_delivery_date", "label": "Date of last delivery", "type": "date" }, { "name": "obs_hist_last_delivery_type", "label": "Type of last delivery", "type": "radio", "options": ["Vaginal", "Cesarean Section"] }, { "name": "obs_hist_last_menstrual_period", "label": "Last menstrual period", "type": "date" }, { "name": "obs_hist_prev_menstrual_period", "label": "Previous menstrual period", "type": "date" }, { "name": "obs_hist_menstrual_flow", "label": "Menstrual flow", "type": "radio", "options": ["scanty (1-2 pads/day)", "moderate (3-5 pads/day)", "heavy (>5 pads/day)"] }, { "name": "obs_hist_dysmenorrhea", "label": "Dysmenorrhea?", "type": "boolean" }, { "name": "obs_hist_hydatidiform_mole", "label": "Hydatidiform mole (within the last 12 months)?", "type": "boolean" }, { "name": "obs_hist_ectopic_pregnancy", "label": "History of ectopic pregnancy?", "type": "boolean" }] },
    { "type": "section", "title": "III. Sexually Transmitted Infections", "subtitle": "Does the client''s partner have any of the following?", "fields": [{ "name": "sti_partner_discharge", "label": "Abnormal discharge from the genital area", "type": "boolean" }, { "name": "sti_partner_sores", "label": "Sores or ulcers in the genital area", "type": "boolean" }, { "name": "sti_partner_pain", "label": "Pain or burning sensation in the genital area", "type": "boolean" }, { "name": "sti_partner_treatment_history", "label": "History of treatment for sexually transmitted infection", "type": "boolean" }, { "name": "sti_partner_hiv_aids_pid", "label": "HIV / AIDS / Pelvic inflammatory disease", "type": "boolean" }] },
    { "type": "section", "title": "IV. Risks for Violence Against Women (VAW)", "subtitle": "Ask the client privately. Does the client''s partner:", "fields": [{ "name": "vaw_unpleasant_relationship", "label": "Have an unpleasant relationship with you?", "type": "boolean" }, { "name": "vaw_partner_disapproval", "label": "Not approve of the visit to FP clinic?", "type": "boolean" }, { "name": "vaw_history", "label": "Have a history of VAW?", "type": "boolean" }, { "name": "vaw_referral", "label": "Referred to:", "type": "checkbox", "options": ["DSWD", "PNP", "NGOs", "Others"] }, { "name": "vaw_referral_specify", "label": "If others, specify", "type": "text" }] },
    { "type": "section", "title": "V. Physical Examination", "fields": [{ "name": "pe_weight_kg", "label": "Weight (kg)", "type": "number" }, { "name": "pe_height_cm", "label": "Height (cm)", "type": "number" }, { "name": "pe_bp", "label": "Blood Pressure (mmHg)", "type": "text" }, { "name": "pe_pulse", "label": "Pulse Rate (/min)", "type": "number" }, { "name": "pe_skin", "label": "Skin", "type": "radio", "options": ["normal", "pale", "jaundice", "hematoma"] }, { "name": "pe_conjunctiva", "label": "Conjunctiva", "type": "radio", "options": ["normal", "pale", "yellowish"] }, { "name": "pe_neck", "label": "Neck", "type": "radio", "options": ["normal", "enlarged thyroid", "enlarged lymph nodes"] }, { "name": "pe_breast", "label": "Breast", "type": "radio", "options": ["normal", "mass", "nipple discharge"] }, { "name": "pe_abdomen", "label": "Abdomen", "type": "radio", "options": ["normal", "abdominal mass", "varicosities"] }, { "name": "pe_extremities", "label": "Extremities", "type": "radio", "options": ["normal", "edema", "varicosities"] }] },
    { "type": "section", "title": "Pelvic Examination (for IUD Acceptors)", "fields": [{ "name": "pelvic_perineum", "label": "Perineum", "type": "radio", "options": ["normal", "warts/lesions", "scars", "swelling"] }, { "name": "pelvic_vaginal_discharge", "label": "Vaginal Discharge", "type": "radio", "options": ["normal", "abnormal", "bloody"] }, { "name": "pelvic_cervical_abnormalities", "label": "Cervical Abnormalities", "type": "radio", "options": ["normal", "erosion", "polyps or cyst", "inflammation or infection", "bloody discharge"] }, { "name": "pelvic_cervical_consistency", "label": "Cervical Consistency", "type": "radio", "options": ["firm", "soft"] }, { "name": "pelvic_cervical_tenderness", "label": "Cervical Tenderness", "type": "boolean" }, { "name": "pelvic_adnexal_tenderness", "label": "Adnexal Tenderness", "type": "boolean" }, { "name": "pelvic_uterine_position", "label": "Uterine Position", "type": "radio", "options": ["mid", "anteflexed", "retroflexed"] }, { "name": "pelvic_uterine_depth", "label": "Uterine Depth (cm)", "type": "number" }] },
    { "type": "section", "title": "Acknowledgement", "fields": [{ "name": "client_signature", "label": "Client Signature (Type Name)", "type": "text" }, { "name": "client_signature_date", "label": "Date", "type": "date" }, { "name": "parent_guardian_signature", "label": "Parent/Guardian Signature (if WRA below 18 y.o.)", "type": "text" }, { "name": "parent_guardian_signature_date", "label": "Date", "type": "date" }] }
  ]
}
$$),
('Family Planning (FP) - Follow-up Note', 'A brief note for follow-up visits for family planning clients.', $$
{
  "fields": [
    { "type": "section", "title": "Follow-up Visit Details", "fields": [{ "name": "medical_findings", "label": "Medical Findings, Observations, and Procedures", "type": "textarea" }, { "name": "method_accepted", "label": "Method Accepted", "type": "text" }, { "name": "provider_signature", "label": "Name of Service Provider (Type Name)", "type": "text" }, { "name": "next_follow_up_date", "label": "Date of Next Follow-up Visit", "type": "date" }] }
  ]
}
$$),
('Pregnancy Risk Assessment', 'A checklist to reasonably ensure a client is not pregnant.', $$
{
  "fields": [
    { "type": "section", "title": "Pregnancy Checklist", "fields": [{ "name": "preg_check_q1", "label": "Do you have a baby less than six (6) months ago, are you fully or nearly-fully breastfeeding, and have you had no menstrual period since then?", "type": "boolean" }, { "name": "preg_check_q2", "label": "Have you abstained from sexual intercourse since your last menstrual period or delivery?", "type": "boolean" }, { "name": "preg_check_q3", "label": "Have you had a baby in the last four (4) weeks?", "type": "boolean" }, { "name": "preg_check_q4", "label": "Did your last menstrual period start within the last seven (7) days?", "type": "boolean" }, { "name": "preg_check_q5", "label": "Have you had a miscarriage or abortion in the last seven (7) days?", "type": "boolean" }, { "name": "preg_check_q6", "label": "Have you been using a reliable contraceptive method consistently and correctly?", "type": "boolean" }] }
  ]
}
$$),
('General Medical Assessment', 'A standard form for general patient intake, covering chief complaint, medical history, and review of systems.', $$
{
  "fields": [
    { "type": "section", "title": "Reason for Visit", "fields": [{ "name": "chief_complaint", "label": "What is the primary reason for your visit today?", "type": "textarea" }, { "name": "history_of_present_illness", "label": "Please describe your symptoms (when they started, what makes them better or worse, etc.)", "type": "textarea" }] },
    { "type": "section", "title": "Vitals", "fields": [{ "name": "vitals_bp", "label": "Blood Pressure", "type": "text" }, { "name": "vitals_hr", "label": "Heart Rate (/min)", "type": "number" }, { "name": "vitals_rr", "label": "Respiratory Rate (/min)", "type": "number" }, { "name": "vitals_temp", "label": "Temperature (°C)", "type": "number" }] },
    { "type": "section", "title": "Past Medical History", "fields": [{ "name": "past_illnesses", "label": "Chronic Illnesses (e.g., Diabetes, Hypertension, Asthma)", "type": "textarea" }, { "name": "past_surgeries", "label": "Past Surgeries or Hospitalizations", "type": "textarea" }, { "name": "medications", "label": "Current Medications (including supplements)", "type": "textarea" }, { "name": "allergies", "label": "Allergies (to medication, food, etc.)", "type": "textarea" }] },
    { "type": "section", "title": "Family History", "fields": [{ "name": "family_history", "label": "Does your immediate family (parents, siblings) have a history of any major illnesses?", "type": "textarea" }] },
    { "type": "section", "title": "Social History", "fields": [{ "name": "social_smoking", "label": "Smoking Status", "type": "radio", "options": ["Never Smoked", "Former Smoker", "Current Smoker"] }, { "name": "social_alcohol", "label": "Alcohol Consumption", "type": "radio", "options": ["None", "Occasional", "Moderate", "Heavy"] }] },
    { "type": "section", "title": "Review of Systems", "subtitle": "Are you currently experiencing any of the following?", "fields": [{ "name": "ros_general_fever", "label": "Fever or Chills", "type": "boolean" }, { "name": "ros_general_weight_loss", "label": "Unexplained Weight Loss", "type": "boolean" }, { "name": "ros_head_headache", "label": "Headaches", "type": "boolean" }, { "name": "ros_eyes_vision_change", "label": "Vision Changes", "type": "boolean" }, { "name": "ros_ent_sore_throat", "label": "Sore Throat", "type": "boolean" }, { "name": "ros_cardio_chest_pain", "label": "Chest Pain", "type": "boolean" }, { "name": "ros_resp_cough", "label": "Cough or Shortness of Breath", "type": "boolean" }, { "name": "ros_gi_nausea", "label": "Nausea or Vomiting", "type": "boolean" }, { "name": "ros_gi_abdominal_pain", "label": "Abdominal Pain", "type": "boolean" }] }
  ]
}
$$),
('General Medical Findings (SOAP Note)', 'A standardized form for providers to document clinical encounters using the SOAP (Subjective, Objective, Assessment, Plan) format.', $$
{
  "fields": [
    { "type": "section", "title": "S: Subjective", "subtitle": "The patient''s report of their symptoms and the history of the present illness.", "fields": [{ "name": "subjective_findings", "label": "Subjective Findings", "type": "textarea" }] },
    { "type": "section", "title": "O: Objective", "subtitle": "The provider''s objective findings from the physical examination and any diagnostic test results.", "fields": [{ "name": "objective_findings", "label": "Objective Findings", "type": "textarea" }] },
    { "type": "section", "title": "A: Assessment", "subtitle": "The provider''s diagnosis or assessment of the patient''s condition.", "fields": [{ "name": "assessment", "label": "Assessment / Diagnosis", "type": "textarea" }] },
    { "type": "section", "title": "P: Plan", "subtitle": "The treatment plan, including medications prescribed, therapies, patient education, and follow-up instructions.", "fields": [{ "name": "plan", "label": "Plan", "type": "textarea" }] }
  ]
}
$$); 