-- Supabase Migration: Seed Comprehensive and More Realistic Mock Provider Data
-- This script adds mock providers with more varied names and randomized schedules.
-- It ensures each clinic has at least one provider for each service category it offers,
-- using real clinic IDs and service categories derived from provided CSV and SQL data.

BEGIN;

-- Data sources reminder (from previous generation):
-- 1. services_rows.csv for service IDs and categories.
-- 2. User-provided SQL for clinic_services table (mapping clinics to service IDs).
-- 3. Target Clinic IDs:
--    '07da576b-b679-4c35-955f-a2e8b6a6dd21' (Tondo)
--    '36184414-d194-4c70-81e3-6f2d50380985' (Cubao)
--    'e33f7836-c4ad-44be-8c11-a860e6cf6452' (Tandang Sora)

-- Placeholder UUIDs will be generated by the script execution within Supabase or manually replaced if needed.
-- The script focuses on providing diverse data that can be copied into Supabase SQL editor.

-- Helper to generate a somewhat random schedule part
-- For actual random generation, a plpgsql function would be better, 
-- but for a one-off seed, we'll just vary a few examples manually in the generated output below.

-- 1. Mock Providers
INSERT INTO public.providers (id, first_name, last_name, specialty, bio, profile_image_url, is_active, created_at, updated_at) VALUES
-- Tondo Clinic Providers
('a1a1a1a1-0001-4001-8001-000000000001', 'Maria', 'Santos', 'Family Planning', 'Dedicated Family Planning specialist at FPOP NCR - Tondo Clinic.', 'https://example.com/profile_images/msantos.jpg', TRUE, NOW(), NOW()),
('a1a1a1a1-0002-4002-8002-000000000002', 'Juan', 'Dela Cruz', 'Maternal Health', 'Experienced in Maternal Health care at FPOP NCR - Tondo Clinic.', 'https://example.com/profile_images/jcruz.jpg', TRUE, NOW(), NOW()),
('a1a1a1a1-0003-4003-8003-000000000003', 'Lina', 'Garcia', 'Child Health', 'Passionate about Child Health services at FPOP NCR - Tondo Clinic.', 'https://example.com/profile_images/lgarcia.jpg', TRUE, NOW(), NOW()),
('a1a1a1a1-0004-4004-8004-000000000004', 'Roberto', 'Reyes', 'Medical', 'General Medical practitioner at FPOP NCR - Tondo Clinic.', 'https://example.com/profile_images/rreyes.jpg', TRUE, NOW(), NOW()),

-- Cubao Clinic Providers
('b2b2b2b2-0001-4001-8001-000000000001', 'Sofia', 'Lim', 'Family Planning', 'Family Planning consultant at FPOP NCR - Cubao Clinic.', 'https://example.com/profile_images/slim.jpg', TRUE, NOW(), NOW()),
('b2b2b2b2-0002-4002-8002-000000000002', 'David', 'Chen', 'Maternal Health', 'Maternal Health expert at FPOP NCR - Cubao Clinic.', 'https://example.com/profile_images/dchen.jpg', TRUE, NOW(), NOW()),
('b2b2b2b2-0003-4003-8003-000000000003', 'Isabelle', 'Tan', 'Reproductive Health', 'Specializing in Reproductive Health at FPOP NCR - Cubao Clinic.', 'https://example.com/profile_images/itan.jpg', TRUE, NOW(), NOW()),
('b2b2b2b2-0004-4004-8004-000000000004', 'Miguel', 'Torres', 'Dental', 'Dental care professional at FPOP NCR - Cubao Clinic.', 'https://example.com/profile_images/mtorres.jpg', TRUE, NOW(), NOW()),
('b2b2b2b2-0005-4005-8005-000000000005', 'Olivia', 'Mercado', 'Medical', 'Providing Medical consultations at FPOP NCR - Cubao Clinic.', 'https://example.com/profile_images/omercado.jpg', TRUE, NOW(), NOW()),

-- Tandang Sora Clinic Providers
('c3c3c3c3-0001-4001-8001-000000000001', 'Carlos', 'Gutierrez', 'Family Planning', 'Family Planning services at FPOP NCR - Tandang Sora Clinic.', 'https://example.com/profile_images/cgutierrez.jpg', TRUE, NOW(), NOW()),
('c3c3c3c3-0002-4002-8002-000000000002', 'Anna', 'Fernandez', 'Maternal Health', 'Maternal Health specialist at FPOP NCR - Tandang Sora Clinic.', 'https://example.com/profile_images/afernandez.jpg', TRUE, NOW(), NOW()),
('c3c3c3c3-0003-4003-8003-000000000003', 'Jose', 'Pascual', 'Laboratory', 'Laboratory services professional at FPOP NCR - Tandang Sora Clinic.', 'https://example.com/profile_images/jpascual.jpg', TRUE, NOW(), NOW());

-- 2. Link Mock Providers to Clinics (Provider Facilities)
INSERT INTO public.provider_facilities (id, provider_id, clinic_id, is_active, created_at, updated_at) VALUES
-- Tondo Links
(gen_random_uuid(), 'a1a1a1a1-0001-4001-8001-000000000001', '07da576b-b679-4c35-955f-a2e8b6a6dd21', TRUE, NOW(), NOW()),
(gen_random_uuid(), 'a1a1a1a1-0002-4002-8002-000000000002', '07da576b-b679-4c35-955f-a2e8b6a6dd21', TRUE, NOW(), NOW()),
(gen_random_uuid(), 'a1a1a1a1-0003-4003-8003-000000000003', '07da576b-b679-4c35-955f-a2e8b6a6dd21', TRUE, NOW(), NOW()),
(gen_random_uuid(), 'a1a1a1a1-0004-4004-8004-000000000004', '07da576b-b679-4c35-955f-a2e8b6a6dd21', TRUE, NOW(), NOW()),
-- Cubao Links
(gen_random_uuid(), 'b2b2b2b2-0001-4001-8001-000000000001', '36184414-d194-4c70-81e3-6f2d50380985', TRUE, NOW(), NOW()),
(gen_random_uuid(), 'b2b2b2b2-0002-4002-8002-000000000002', '36184414-d194-4c70-81e3-6f2d50380985', TRUE, NOW(), NOW()),
(gen_random_uuid(), 'b2b2b2b2-0003-4003-8003-000000000003', '36184414-d194-4c70-81e3-6f2d50380985', TRUE, NOW(), NOW()),
(gen_random_uuid(), 'b2b2b2b2-0004-4004-8004-000000000004', '36184414-d194-4c70-81e3-6f2d50380985', TRUE, NOW(), NOW()),
(gen_random_uuid(), 'b2b2b2b2-0005-4005-8005-000000000005', '36184414-d194-4c70-81e3-6f2d50380985', TRUE, NOW(), NOW()),
-- Tandang Sora Links
(gen_random_uuid(), 'c3c3c3c3-0001-4001-8001-000000000001', 'e33f7836-c4ad-44be-8c11-a860e6cf6452', TRUE, NOW(), NOW()),
(gen_random_uuid(), 'c3c3c3c3-0002-4002-8002-000000000002', 'e33f7836-c4ad-44be-8c11-a860e6cf6452', TRUE, NOW(), NOW()),
(gen_random_uuid(), 'c3c3c3c3-0003-4003-8003-000000000003', 'e33f7836-c4ad-44be-8c11-a860e6cf6452', TRUE, NOW(), NOW());

-- 3. Add Varied Weekly Schedules for Mock Providers
INSERT INTO public.provider_weekly_schedules (id, provider_id, facility_id, schedule_type, schedule_data, status, timezone, created_at, updated_at) VALUES
-- Maria Santos (Tondo, Family Planning) - Mon, Wed, Fri AM
(gen_random_uuid(), 'a1a1a1a1-0001-4001-8001-000000000001', '07da576b-b679-4c35-955f-a2e8b6a6dd21', 'weekly', '{ "monday": [{"start_time": "08:00", "end_time": "12:00"}], "wednesday": [{"start_time": "09:00", "end_time": "13:00"}], "friday": [{"start_time": "08:30", "end_time": "12:30"}] }', 'active', 'Etc/UTC', NOW(), NOW()),
-- Juan Dela Cruz (Tondo, Maternal Health) - Tue, Thu Full Day
(gen_random_uuid(), 'a1a1a1a1-0002-4002-8002-000000000002', '07da576b-b679-4c35-955f-a2e8b6a6dd21', 'weekly', '{ "tuesday": [{"start_time": "09:00", "end_time": "17:00"}], "thursday": [{"start_time": "10:00", "end_time": "18:00"}] }', 'active', 'Etc/UTC', NOW(), NOW()),
-- Lina Garcia (Tondo, Child Health) - Mon-Fri PM with break
(gen_random_uuid(), 'a1a1a1a1-0003-4003-8003-000000000003', '07da576b-b679-4c35-955f-a2e8b6a6dd21', 'weekly', '{ "monday": [{"start_time": "13:00", "end_time": "17:00"}], "tuesday": [{"start_time": "13:00", "end_time": "17:00"}], "wednesday": [{"start_time": "13:00", "end_time": "17:00"}], "thursday": [{"start_time": "13:00", "end_time": "17:00"}], "friday": [{"start_time": "13:00", "end_time": "16:00"}] }', 'active', 'Etc/UTC', NOW(), NOW()),
-- Roberto Reyes (Tondo, Medical) - Mon, Tue, Wed Full Day
(gen_random_uuid(), 'a1a1a1a1-0004-4004-8004-000000000004', '07da576b-b679-4c35-955f-a2e8b6a6dd21', 'weekly', '{ "monday": [{"start_time": "09:00", "end_time": "17:00"}], "tuesday": [{"start_time": "09:00", "end_time": "17:00"}], "wednesday": [{"start_time": "09:00", "end_time": "16:00"}] }', 'active', 'Etc/UTC', NOW(), NOW()),

-- Sofia Lim (Cubao, Family Planning) - Mon, Wed 9-5
(gen_random_uuid(), 'b2b2b2b2-0001-4001-8001-000000000001', '36184414-d194-4c70-81e3-6f2d50380985', 'weekly', '{ "monday": [{"start_time": "09:00", "end_time": "17:00"}], "wednesday": [{"start_time": "09:00", "end_time": "17:00"}] }', 'active', 'Etc/UTC', NOW(), NOW()),
-- David Chen (Cubao, Maternal Health) - Tue 10-6, Fri 9-1
(gen_random_uuid(), 'b2b2b2b2-0002-4002-8002-000000000002', '36184414-d194-4c70-81e3-6f2d50380985', 'weekly', '{ "tuesday": [{"start_time": "10:00", "end_time": "18:00"}], "friday": [{"start_time": "09:00", "end_time": "13:00"}] }', 'active', 'Etc/UTC', NOW(), NOW()),
-- Isabelle Tan (Cubao, Reproductive Health) - Mon, Thu, Fri 8-4
(gen_random_uuid(), 'b2b2b2b2-0003-4003-8003-000000000003', '36184414-d194-4c70-81e3-6f2d50380985', 'weekly', '{ "monday": [{"start_time": "08:00", "end_time": "16:00"}], "thursday": [{"start_time": "08:00", "end_time": "16:00"}], "friday": [{"start_time": "08:00", "end_time": "16:00"}] }', 'active', 'Etc/UTC', NOW(), NOW()),
-- Miguel Torres (Cubao, Dental) - Mon-Thu 9-6
(gen_random_uuid(), 'b2b2b2b2-0004-4004-8004-000000000004', '36184414-d194-4c70-81e3-6f2d50380985', 'weekly', '{ "monday": [{"start_time": "09:00", "end_time": "18:00"}], "tuesday": [{"start_time": "09:00", "end_time": "18:00"}], "wednesday": [{"start_time": "09:00", "end_time": "18:00"}], "thursday": [{"start_time": "09:00", "end_time": "18:00"}] }', 'active', 'Etc/UTC', NOW(), NOW()),
-- Olivia Mercado (Cubao, Medical) - Wed, Fri 10-5
(gen_random_uuid(), 'b2b2b2b2-0005-4005-8005-000000000005', '36184414-d194-4c70-81e3-6f2d50380985', 'weekly', '{ "wednesday": [{"start_time": "10:00", "end_time": "17:00"}], "friday": [{"start_time": "10:00", "end_time": "17:00"}] }', 'active', 'Etc/UTC', NOW(), NOW()),

-- Carlos Gutierrez (Tandang Sora, Family Planning) - Mon-Fri 9-12, 1-5 (with break)
(gen_random_uuid(), 'c3c3c3c3-0001-4001-8001-000000000001', 'e33f7836-c4ad-44be-8c11-a860e6cf6452', 'weekly', '{ "monday": [{"start_time": "09:00", "end_time": "12:00"}, {"start_time": "13:00", "end_time": "17:00"}], "tuesday": [{"start_time": "09:00", "end_time": "12:00"}, {"start_time": "13:00", "end_time": "17:00"}], "wednesday": [{"start_time": "09:00", "end_time": "12:00"}, {"start_time": "13:00", "end_time": "17:00"}], "thursday": [{"start_time": "09:00", "end_time": "12:00"}, {"start_time": "13:00", "end_time": "17:00"}], "friday": [{"start_time": "09:00", "end_time": "12:00"}, {"start_time": "13:00", "end_time": "17:00"}] }', 'active', 'Etc/UTC', NOW(), NOW()),
-- Anna Fernandez (Tandang Sora, Maternal Health) - Tue, Wed, Thu 8-3
(gen_random_uuid(), 'c3c3c3c3-0002-4002-8002-000000000002', 'e33f7836-c4ad-44be-8c11-a860e6cf6452', 'weekly', '{ "tuesday": [{"start_time": "08:00", "end_time": "15:00"}], "wednesday": [{"start_time": "08:00", "end_time": "15:00"}], "thursday": [{"start_time": "08:00", "end_time": "15:00"}] }', 'active', 'Etc/UTC', NOW(), NOW()),
-- Jose Pascual (Tandang Sora, Laboratory) - Mon, Fri 10-4
(gen_random_uuid(), 'c3c3c3c3-0003-4003-8003-000000000003', 'e33f7836-c4ad-44be-8c11-a860e6cf6452', 'weekly', '{ "monday": [{"start_time": "10:00", "end_time": "16:00"}], "friday": [{"start_time": "10:00", "end_time": "16:00"}] }', 'active', 'Etc/UTC', NOW(), NOW());

COMMIT; 