-- 1. Create the user_medications table
CREATE TABLE public.user_medications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    dosage TEXT, -- e.g., "500mg", "1 tablet"
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
COMMENT ON TABLE public.user_medications IS 'Stores the list of medications for each user.';

-- 2. Create the medication_logs table
CREATE TABLE public.medication_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medication_id UUID NOT NULL REFERENCES public.user_medications(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, -- Denormalized for simpler RLS
    taken_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
COMMENT ON TABLE public.medication_logs IS 'Records each time a user marks a medication dose as taken.';

-- 3. Add Indexes
CREATE INDEX idx_user_medications_user_id ON public.user_medications(user_id);
CREATE INDEX idx_medication_logs_medication_id ON public.medication_logs(medication_id);
CREATE INDEX idx_medication_logs_user_id_taken_at ON public.medication_logs(user_id, taken_at DESC);

-- 4. Enable RLS
ALTER TABLE public.user_medications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medication_logs ENABLE ROW LEVEL SECURITY;

-- 5. Define RLS Policies
-- Users can manage their own medication list
CREATE POLICY "Users can manage their own medications"
ON public.user_medications FOR ALL
TO authenticated USING (auth.uid() = user_id);

-- Users can manage their own medication logs
CREATE POLICY "Users can manage their own medication logs"
ON public.medication_logs FOR ALL
TO authenticated USING (auth.uid() = user_id); 